help:		## show this help
	@fgrep -h "##" $(MAKEFILE_LIST) | fgrep -v fgrep


Catalogue:  ## Install catalogue
		@bash components/catalogue.sh
Mongodb:	## Install mongodb
		@bash components/mongodb.sh
Redis:	    ## Install Redis
		@bash components/redis.sh
user:    	## Install user
		@bash components/user.sh
Cart:    	 ## Install cart
		@bash components/cart.sh
Mysql:	      ## Install mysql
		@bash components/mysql.sh
shipping:  	## Install shipping
		@bash components/shipping.sh
Rabbitmq:    ## Install Rabbitmq
		@bash components/rabbitmq
payment:  	## Install payment
		@bash components/payment.sh
Frontend:	 ## Install Frontend
		@bash componenets/frontend.sh