help:		## show this help
	@fgrep -h "##" $(MAKEFILE_LIST) | fgrep -v fgrep


catalogue:  ## Install catalogue
		@bash components/catalogue.sh
Mongodb:	## Install Mongodb
		@bash components/mongodb.sh
redis:	    ## Install Redis
		@bash components/redis.sh
user:    	## Install user
		@bash components/user.sh
cart:    	    ## Install cart
		@bash components/cart.sh
mysql:	        ## Install mysql
		@bash components/mysql.sh
shipping:   	## Install shipping
		@bash components/shipping.sh
payment:  	## Install payment
		@bash components/payment.sh
frontend:	 ## Install Frontend
		@bash components/frontend.sh
rabbitmq:    ## INSTALL